/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package com.github.derghust.flinkblaze

import org.scalatest.funsuite.AnyFunSuite
import org.junit.runner.RunWith
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class AsyncOperatorImpl extends AnyFunSuite {
  // TODO Implement test for AsyncOperatorImpl with apache flink stream test
}
