/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package com.github.derghust.flinkblaze

import org.apache.flink.streaming.api.scala.DataStream

object Blaze {
implicit class AsyncOperator[T](ds: DataStream[T]) {

}
}

// ds.
class Library {
  def someLibraryMethod(): Boolean = true
}
